### PR TITLE
Add another known xmem job name

### PR DESCRIPTION
**Pull request by John-A-Davies**
Fix KNOWN_XMEM_JOB_NAMES="ZWESIS01 ZWEXMSTC ZWESISTC" in `uninstall-zowe.sh`

### CODE REVIEW

**Comment by John-A-Davies** [comment]
To be certain of eliminating all old versions of a PROCLIB member, you need to scan all PROCLIB datasets in the JES concatenation, not just the PROCLIB dataset that the user nominates this time around.

**Comment by jackjia-ibm** [comment]
Is variable `PROCLIBS` in the script good enough? If not, could you please propose a change here? Thanks.

**Comment by John-A-Davies** [comment]
Fortunately, `uninstall-zowe.sh` already does this, so it should be possible to amend line 244
```
if [ "${member}" = "${ZOWE_PROCLIB}" ]; then
```
to deal with a list of candidate members to be deleted.

**Comment by John-A-Davies** [comment]
I think this is already implemented.  
```
for proclib in $PROCLIBS
...
    for ZOWE_PROCLIB in $KNOWN_ZOWE_PROCLIB_NAMES; do
...
for proclib in $PROCLIBS
...
    for XMEM_PROCLIB in $KNOWN_XMEM_PROCLIB_NAMES; do
```

**Pull request merged**
